config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'dashboard#home'

  resource :dashboard, controller: :dashboard, only: [] do
    get :chart_data
    get :summary
  end

  resource :profile, only: %i[edit update]

  resources :trades, only: %i[create]

  resources :wallets do
    get :total, on: :member
  end

  resources :coins do
    get :total, on: :member
    get :reference_price, on: :member
    get :market_value, on: :member
    get :variation_from_reference, on: :member

    resources :trades, only: %i[index new create destroy]
  end

  resources :coin_wallets, only: [] do
    get :quantity, on: :collection
    get :total, on: :collection
    post :create_or_update, on: :collection
  end

  resources :api, only: [] do
    get :list, on: :collection
    get :prices, on: :collection
  end

  resources :gecko_coins, only: [] do
    get :search, on: :collection
  end

  resource :config, controller: :config

  resources :app_processes, only: :show

  resources :snapshots, only: %i[index] do
    get :request_snap, on: :collection
  end

  resource :backup, only: [] do
    get :import, on: :collection
    get :export, on: :collection
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < AuthenticatedController
  before_action :load_data, only: %i[home]
  before_action :load_coins, only: %i[home chart_data]

  layout false, only: :summary

  def home; end

  def chart_data
    render json: generate_chart_data
  end

  def summary; end

  private

  def generate_chart_data
    coins = @coins.all.sort_by { |coin| coin.currency_value(@main_currency) }
    {
      labels: compute_labels(coins),
      values: compute_values(coins)
    }
  end

  def compute_labels(coins)
    coins.pluck(:name)
  end

  def compute_values(coins)
    total_value = current_user.wealth.total_value(@main_currency)
    coins.map { |coin| (coin.currency_value(@main_currency) / total_value * 100).round(2) }
  end

  def load_data
    @wallets = current_user.wallets.order(:name)
    @coin_wallets = current_user.coin_wallets.all
  end

  def load_coins
    @coins = current_user.coins.order(:name)
    @coins = @coins.visible unless params[:display_all]
  end
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
  def total_variation(user)
    delta = user.wealth.delta_percent
    return '-' unless delta

    direction = delta >= 0 ? 'green' : 'red'
    tag.span class: direction do
      "#{number_with_precision(delta, precision: 2)} %"
    end
  end

  def variation_from_reference(coin)
    delta = coin.variation_from_reference
    klass = delta >= 0 ? 'green' : 'red'
    tag.span(class: klass) do
      "#{number_with_precision delta, precision: 2} %"
    end
  end

  def get_quantity(coin_wallets, coin_id, wallet_id)
    coin_wallet = coin_wallets.find do |cw|
      cw.coin_id == coin_id && cw.wallet_id == wallet_id
    end
    quantity = coin_wallet&.quantity
    format_positive_number(quantity)
  end

  def get_wallet_total(wallets, wallet_id, currency)
    value = wallets.find { |wallet| wallet.id == wallet_id }&.currency_value(currency)
    format_positive_number(value)
  end

  def get_coin_total(coins, coin_id, currency)
    coin = coins.find { |coin| coin.id == coin_id }
    value = if currency
              coin.currency_value(currency)
            else
              coin.total_quantity
            end
    format_positive_number(value)
  end

  def get_main_total(current_user, currency)
    total = current_user.wealth.total_value(currency)
    format_positive_number(total)
  end

  def format_positive_number(value, precision: nil)
    formatted_value = (value || 0).positive? ? value : '-'
    number_with_precision formatted_value, precision: current_user.precision || default_precision
  end

  def format_number(value, precision: nil)
    number_with_precision value, precision: current_user.precision || default_precision
  end

  def default_precision
    4
  end
end

app/views/dashboard/_actions.html.erb
  <div class='buttons'>
    <%= button_tag "Mettre à jour la liste des Cryptos", 
                   class:"btn btn-outline-info btn-sm",
                   data: {controller: 'button',
                          'button-url-value' => list_api_index_path,
                          'action': 'click->button#load' } do %>
      <span class="spinner hidden spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
      <span> <%= t '.update_list' %> </span>
    <%end %>

    <%= button_tag "Mettre à jour les prix", 
                   class:"btn btn-outline-info btn-sm",
                   data: {controller: 'button',
                          'button-url-value' => prices_api_index_path,
                          'action': 'click->button#load' } do %>
      <span class="spinner hidden spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
      <span> <%= t('.update_prices') %> </span>
    <% end %>

    <%= button_tag "Snapshot", 
                   class:"btn btn-outline-info btn-sm",
                   data: {controller: 'button',
                          'button-url-value' => request_snap_snapshots_path,
                          'action': 'click->button#load' } do %>
      <span class="spinner hidden spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
      <span> <%= t('.snapshot') %> </span>
    <% end %>

    <%= button_tag "Backup", 
                   class:"btn btn-outline-info btn-sm",
                   style: 'display: none',
                   data: {controller: 'button',
                          'button-url-value' => export_backup_path,
                          'action': 'click->button#load' } do %>
      <span class="spinner hidden spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
      <span> <%= t '.backup' %> </span>
    <% end %>
  </div>

app/views/dashboard/_cell_form.html.erb
<% quantity =  get_quantity(@coin_wallets, coin.id, wallet.id) %>

<td  data-controller="dynamic-field" 
     data-action="click->dynamic-field#displayForm"
     data-dynamic-field-url-value="<%= quantity_coin_wallets_path(coin_id: coin.id, wallet_id: wallet.id) %>"
     data-dynamic-field-coin-value="<%= coin.id %>"
     data-dynamic-field-wallet-value="<%= wallet.id %>"
     class='user-input'>
    <div class='text-end quantity-value' 
         data-dynamic-field-target="display"><%= quantity %></div>
    <%= form_with url: create_or_update_coin_wallets_path(coin_id: coin.id, wallet_id: wallet.id),
                  remote: true, local: false,
                  data: {action: "ajax:error->dynamic-field#handleError 
                                  ajax:success->dynamic-field#handleSuccess 
                                  add-trade@window->dynamic-field#reloadQuantity"} do %>
    <%= hidden_field_tag :quantity, nil, 
                          class: "form-control form-control-sm", 
                          data: { 'action' => "focusout->dynamic-field#updateValue",
                                  'dynamic-field-target' => "input" } %>
    <% end %>
</td>

app/views/dashboard/_coin_total.html.erb
<% coin_total = get_coin_total(@coins, coin_id, currency) %>

<td  data-controller="template" 
     data-template-url-value="<%= total_coin_path(coin_id, currency: currency) %>"
     data-template-coin-value="<%= coin_id %>"
     data-template-wallet-value=""
     data-action="update-quantity@window->template#reload update-data@window->template#reload"
     >
  <div class='text-end' data-template-target="template"><%= coin_total %></div>
</td>

app/views/dashboard/_home_content.html.erb
<div class='top-row'>
  <div>
    <div class="template"
          data-controller='template'
          data-template-url-value="<%= summary_dashboard_path %>"
          data-template-coin-value=""
          data-template-wallet-value=""
          data-action="update-quantity@window->template#reload update-data@window->template#reload">
      <div data-template-target="template">
        <%= render 'summary' %>
      </div>
    </div>
    <%= render 'actions' %>
  </div>
  <%= render 'components/calculator' %>
</div>  

<%= render 'trade_form' %>


<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="tableau-tab" data-bs-toggle="tab" data-bs-target="#tableau" type="button" role="tab" aria-controls="tableau" aria-selected="false">Tableau</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="graph-tab" data-bs-toggle="tab" data-bs-target="#graph" type="button" role="tab" aria-controls="graph" aria-selected="true">Graphique</button>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
<div class="tab-pane fade show active" id="tableau" role="tabpanel" aria-labelledby="tableau-tab">
  <%= render 'dashboard/table/table_content' %>
</div>
<div class="tab-pane fade" id="graph" role="tabpanel" aria-labelledby="graph-tab">
  <div id="pie-chart" data-controller='chart'
                    data-chart-url-value="<%= chart_data_dashboard_path %>">
    <div class="text-center spinner-container">
      <div class="spinner-border text-secondary" role="status" id='graph-spinner'>
        <span class="visually-hidden"><%= t 'app.events.loading' %></span>
      </div>
    </div>
    <canvas id="wallet-pie" width="400" height="400">
    </canvas>
  </div>
</div>

app/views/dashboard/_home_not_ready.html.erb
<div class="alert alert-info" role="alert">
  <h4 class="alert-heading"><%= t('.empty') %></h4>
  <p><%= t('.general-info') %></p>
  <hr>
  <% if @coins.empty? %>
    <div><%= t('.no_coin') %></div>
    <%= icon_link_to t('.add_coin'), "fab fa-bitcoin", new_coin_path %>
  <% end %>
  <% if @wallets.empty? %>
    <div><%= t('.no_wallet') %></div>
    <%= icon_link_to t('.add_wallet'), "fas fa-lock", new_wallet_path %>
  <% end %>
  </div>

app/views/dashboard/_main_total.html.erb
<% main_total = get_main_total(current_user, currency) %>

<th scope='row'  data-controller="template" 
     data-template-url-value="<%= total_coin_wallets_path(currency: currency) %>"
     data-template-coin-value=""
     data-template-wallet-value=""
     data-action="update-quantity@window->template#reload update-data@window->template#reload"
     >
  <div class='text-end' data-template-target="template"><%= main_total %></div>
</th>

app/views/dashboard/_summary.html.erb
<div>
  <%= "#{t('.investment')} #{@investment_currency&.upcase}" %> 
  <%= number_with_precision(current_user.investment, precision: 2) %> 
</div>
<div>
  <%= "#{t('.current_value')} #{@investment_currency&.upcase}" %> 
  <%= number_with_precision(current_user.wealth.total_ref_value, precision: 2) %>
</div>
<div>
  <%= t '.delta' %><%= total_variation(current_user) %> 
</div>

app/views/dashboard/_toggle_visible_coins.html.erb
<div class=''>
  <% if params[:display_all] %>
    <%= icon_link_to("Masquer inactifs", "far fa-eye-slash", root_path) %>
  <% else %>
    <%= icon_link_to("Afficher tous", "far fa-eye", root_path(display_all: true)) %>
  <% end %>
</div>

app/views/dashboard/_trade_form.html.erb
<div data-controller='trade-form'>
  <div data-trade-form-target='formWrapper' class='segment trade-form'>
    <%= render 'trades/inline_form' %>
  </div>
</div>

app/views/dashboard/_wallet_total.html.erb
<% wallet_total = get_wallet_total(@wallets, wallet_id, currency) %>

<td  data-controller="template" 
     data-template-url-value="<%= total_wallet_path(wallet_id, currency: currency) %>"
     data-template-coin-value=""
     data-template-wallet-value="<%= wallet_id %>"
     data-action="update-quantity@window->template#reload 
                  update-data@window->template#reload"
     >
  <div class='text-end' data-template-target="template">
    <%= wallet_total %>
  </div>
</td>

app/views/dashboard/home.html.erb
<div class='home'>
  <h1><%= t '.title' %></h1>
  <% if @wallets.present? && @coins.present?%>
    <%= render 'home_content' %>
  <% else %>
    <%= render 'home_not_ready' %>
  <% end %>
</div>

app/views/dashboard/summary.html.erb
<%= render 'summary' %>