config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'dashboard#home'

  resource :dashboard, controller: :dashboard, only: [] do
    get :chart_data
    get :summary
  end

  resource :profile, only: %i[edit update]

  resources :trades, only: %i[create]

  resources :wallets do
    get :total, on: :member
  end

  resources :coins do
    get :total, on: :member
    get :reference_price, on: :member
    get :market_value, on: :member
    get :variation_from_reference, on: :member

    resources :trades, only: %i[index new create destroy]
  end

  resources :coin_wallets, only: [] do
    get :quantity, on: :collection
    get :total, on: :collection
    post :create_or_update, on: :collection
  end

  resources :api, only: [] do
    get :list, on: :collection
    get :prices, on: :collection
  end

  resources :gecko_coins, only: [] do
    get :search, on: :collection
  end

  resource :config, controller: :config

  resources :app_processes, only: :show

  resources :snapshots, only: %i[index] do
    get :request_snap, on: :collection
  end

  resource :backup, only: [] do
    get :import, on: :collection
    get :export, on: :collection
  end
end

app/models/wallet.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: wallets
#
#  id          :uuid             not null, primary key
#  name        :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :uuid
#
class Wallet < ApplicationRecord
  belongs_to :user
  has_many :coin_wallets
  has_many :coins, through: :coin_wallets
  validates :name, presence: true, uniqueness: { scope: :user_id }

  # %w[usd eur btc].each do |currency|
  #   define_method "#{currency}_value" do
  #     coin_wallets.inject(0) do |sum, coin_wallet|
  #       sum += coin_wallet.currency_value(currency)
  #     end
  #   end
  # end

  def currency_value(currency)
    coin_wallets.inject(0) do |sum, coin_wallet|
      sum += coin_wallet.currency_value(currency)
    end
  end
end

app/controllers/wallets_controller.rb
# frozen_string_literal: true

class WalletsController < AuthenticatedController
  before_action :load_wallets, only: %i[index new create]
  before_action :load_wallet, only: %i[edit total update]
  layout false, only: :total

  def new
    @wallet = @wallets.new
  end

  def index; end

  def edit; end

  def create
    @wallet = @wallets.create(allowed_params)
    if @wallet.save
      redirect_to wallets_path, notice: 'Success!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @wallet.update(allowed_params)
      redirect_to coins_path, notice: 'Success!'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def total
    @currency_value = @wallet.currency_value(params['currency'])
  end

  private

  def allowed_params
    params.require(:wallet).permit(:name, :description)
  end

  def load_wallets
    @wallets = current_user.wallets
  end

  def load_wallet
    @wallet = current_user.wallets.find(params[:id])
  end
end

app/views/wallets/_form.html.erb
<%= form_for @wallet, url: url, method: method do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, required: true, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
    <div class='field-warning'><%= t('.warning') %></div>
  </div>
  <%= form.submit action, class: "btn btn-info" %>
<% end %>

app/views/wallets/edit.html.erb
<h1><%=" #{t 'app.actions.edit'} #{@wallet.name}" %></h1>

<%= render 'form', url: wallet_path(@wallet), method: :put, action: t('app.actions.update') %>

app/views/wallets/index.html.erb
<h1><%= t '.title' %></h1>

<table class='table table-sm'>
  <thead>
    <tr>
      <th scope='col'><%= Wallet.human_attribute_name(:name) %></th>
      <th scope='col'><%= Wallet.human_attribute_name(:description) %></th>
      <th scope='col'></th>
    </tr>
  </thead>
  <tbody>
    <% @wallets.each do |wallet| %>
      <tr>
        <td><%= wallet.name %></td>
        <td><%= wallet.description %></td>
        <td class='text-end'>
          <%= icon_link_to('Modifier', "far fa-edit",  edit_wallet_path(wallet)) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to t('.new'), new_wallet_path, class: 'btn btn-info' %>

app/views/wallets/new.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form', method: :create, url: wallets_path, action: t('app.actions.create') %>

app/views/wallets/total.html.erb
<%= number_with_precision @currency_value, precision: current_user.precision %>