config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'dashboard#home'

  resource :dashboard, controller: :dashboard, only: [] do
    get :chart_data
    get :summary
  end

  resource :profile, only: %i[edit update]

  resources :trades, only: %i[create]

  resources :wallets do
    get :total, on: :member
  end

  resources :coins do
    get :total, on: :member
    get :reference_price, on: :member
    get :market_value, on: :member
    get :variation_from_reference, on: :member

    resources :trades, only: %i[index new create destroy]
  end

  resources :coin_wallets, only: [] do
    get :quantity, on: :collection
    get :total, on: :collection
    post :create_or_update, on: :collection
  end

  resources :api, only: [] do
    get :list, on: :collection
    get :prices, on: :collection
  end

  resources :gecko_coins, only: [] do
    get :search, on: :collection
  end

  resource :config, controller: :config

  resources :app_processes, only: :show

  resources :snapshots, only: %i[index] do
    get :request_snap, on: :collection
  end

  resource :backup, only: [] do
    get :import, on: :collection
    get :export, on: :collection
  end
end

app/views/layouts/_flash.html.erb
<div class="hidden flash alert alert-success " role="alert" id='flash'>

</div>


<% flash.each do |type, message| %>
  <% mapped_type = type == 'notice' ? 'success' : 'warning' %>
  <div class="event-notice alert alert-<%= mapped_type %> alert-dismissible fade show" role="alert">
    <%= message %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div class="disclaimer">
/!\ VERSION DE DEMO, POUVANT PRESENTER DES BUGS ET NON SECURISEE. NE PAS UTILISER AVEC DES DONNEES REELLES /!\
</div>
<nav>
  <div class=submenu>
      <div class='item'>
        <%= link_to t('nav.home'), root_path %>
      </div>
    <% if user_signed_in?%>
      <div class='item'>
        <%= link_to t('nav.overview'), root_path %>
      </div>
      <div class='item'>
        <%= link_to t('nav.wallets'), wallets_path %>
      </div>
      <div class='item'>
        <%= link_to t('nav.coins'), coins_path %>
      </div>
      <div class='item'>
        <%= link_to t('nav.snapshots'), snapshots_path %>
      </div>
    <% end %>
  </div>
  <div class='submenu'>
    <% if user_signed_in?%>
      <div class='item'>
        <%= link_to t('nav.edit_user'), edit_profile_path %>
      </div>
      <div class='item'>
        <%= link_to t('nav.logout'), destroy_user_session_path, method: :delete %>
      </div>
    <% end %>
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wallets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>

  <body data-controller="app" class="<%= params[:controller].split('/').join( ' ') %>">
    <%= render 'layouts/header' %>
    <div class='main-container'>
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
    
  </body>
</html>