config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'dashboard#home'

  resource :dashboard, controller: :dashboard, only: [] do
    get :chart_data
    get :summary
  end

  resource :profile, only: %i[edit update]

  resources :trades, only: %i[create]

  resources :wallets do
    get :total, on: :member
  end

  resources :coins do
    get :total, on: :member
    get :reference_price, on: :member
    get :market_value, on: :member
    get :variation_from_reference, on: :member

    resources :trades, only: %i[index new create destroy]
  end

  resources :coin_wallets, only: [] do
    get :quantity, on: :collection
    get :total, on: :collection
    post :create_or_update, on: :collection
  end

  resources :api, only: [] do
    get :list, on: :collection
    get :prices, on: :collection
  end

  resources :gecko_coins, only: [] do
    get :search, on: :collection
  end

  resource :config, controller: :config

  resources :app_processes, only: :show

  resources :snapshots, only: %i[index] do
    get :request_snap, on: :collection
  end

  resource :backup, only: [] do
    get :import, on: :collection
    get :export, on: :collection
  end
end

app/models/coin.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: coins
#
#  id              :uuid             not null, primary key
#  name            :string
#  code            :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  gecko_coin_id   :uuid
#  reference_price :decimal(, )
#  hide            :boolean          default(FALSE)
#  user_id         :uuid
#
class Coin < ApplicationRecord
  belongs_to :gecko_coin
  belongs_to :user

  has_many :coin_wallets
  has_many :wallets, through: :coin_wallets
  has_many :transactions

  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :code, presence: true, uniqueness: { scope: :user_id }

  delegate :api_id, to: :gecko_coin

  scope :visible, lambda {
    where.not(hide: true)
  }

  def trades
    user.trades.where("buy_coin_id = :id or sell_coin_id = :id", id: id)
  end

  def transaction_currencies
    transactions.pluck(:reference_currency).uniq
  end

  def market_value(currency)
    return nil if gecko_coin_id.nil? || currency.blank?

    gecko_coin.send("market_value_#{currency}")
  end

  def display_name
    "#{name} (#{code.upcase})"
  end

  def display_code
    "#{code.upcase} (#{name})"
  end

  def total_quantity
    coin_wallets.inject(0) do |acc, coin_wallet|
      acc += coin_wallet.quantity
      acc
    end
  end

  def total_buy_quantity
    buy_transactions.inject(0) do |sum, transaction|
      sum += transaction.quantity
    end
  end

  def total_investment
    buy_transactions.inject(0) do |sum, transaction|
      sum += transaction.price_reference_currency * transaction.quantity
    end
  end

  def total_sold_value
    sell_transactions.inject(0) do |sum, transaction|
      sum += transaction.price_reference_currency * transaction.quantity
    end
  end

  def total_sell_quantity
    sell_transactions.inject(0) do |sum, transaction|
      sum += transaction.quantity
    end
  end

  def total_buy_quantity
    buy_transactions.inject(0) do |sum, transaction|
      sum += transaction.quantity
    end
  end

  def total_sell_quantity
    sell_transactions.inject(0) do |sum, transaction|
      sum += transaction.quantity
    end
  end

  def remaining_quantity
    total_buy_quantity - total_sell_quantity
  end

  def current_value_in_wallet(currency)
    remaining_quantity * market_value(currency)
  end

  def net_result
    current_value_in_wallet(user.main_currency) + total_sold_value - total_investment
  end

  def average_buy_price
    return 0 if buy_transactions.empty?

    total_investment / total_buy_quantity
  end

  def average_sell_price
    return 0 if sell_transactions.empty?

    total_sold_value / total_sell_quantity
  end

  # def average_sell_price
  #   return 0 if transactions.sell.empty?

  #   total_value = transactions.sell.inject(0) do |sum, transaction|
  #     sum += transaction.price_usd * transaction.quantity
  #   end
  #   total_value / total_sell_quantity
  # end

  def currency_value(currency)
    coin_wallets.inject(0) do |sum, coin_wallet|
      sum += coin_wallet.currency_value(currency)
    end
  end

  def variation_from_reference
    return 0 unless market_value(user.main_currency).present? && reference_price.present?

    ((market_value(user.main_currency) / reference_price) - 1) * 100
  end

  private

  def buy_transactions
    @buy_transactions ||= transactions.buy.for_currency(user.main_currency)
  end

  def sell_transactions
    @sell_transactions ||= transactions.sell.for_currency(user.main_currency)
  end
end

app/controllers/coins_controller.rb
# frozen_string_literal: true

class CoinsController < AuthenticatedController
  before_action :load_coins, only: %i[new index create]
  before_action :load_coin, only: %i[total edit update reference_price
                                     market_value variation_from_reference]

  layout false, only: %i[total reference_price market_value variation_from_reference]

  def new
    @coin = @coins.new
  end

  def index; end

  def edit; end

  def update
    if @coin.update(allowed_params)
      redirect_to coins_path, notice: 'Success!'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    @coin = @coins.new(allowed_params)
    set_name_and_code
    if @coin.save
      redirect_to coins_path, notice: 'Success!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def total
    currency = params['currency']
    @total_quantity = compute_total(currency)
  end

  def reference_price; end

  def market_value
    value = @coin.market_value(params['currency'])&.round(current_user.precision)

    render json: { value: value }
  end

  def variation_from_reference; end

  private

  def compute_total(currency)
    return @coin.total_quantity if currency.nil?

    @currency_value = @coin.currency_value(params['currency'])
  end

  def allowed_params
    params.require(:coin).permit(:name, :code, :gecko_coin_id, :reference_price, :hide)
  end

  def load_coins
    @coins = current_user.coins.order(:name)
  end

  def load_coin
    @coin = current_user.coins.find(params[:id])
  end

  def set_name_and_code
    return if @coin.gecko_coin.nil?

    @coin.name = @coin.gecko_coin.name if @coin.name.nil?
    @coin.code = @coin.gecko_coin.code if @coin.code.nil?
  end
end

app/views/coins/_form.html.erb
<%= form_for @coin, url: url, method: method do |form| %>
  <div class="mb-3" 
      data-controller='search-dropdown'
      data-search-dropdown-url-value="<%= search_gecko_coins_path %>">
    <%= form.label :gecko_coin, class: "form-label" %>
    <%= text_field_tag :gecko_coin, '', class: "form-control", 
                       data: {action: "input->search-dropdown#load"} %>
    <div data-search-dropdown-target='results'></div>
    <%#= form.hidden_field :gecko_coin_id,
                          data: {'search-dropdown-target' => 'input'} %>
  </div>
  <div class="mb-3">
    <%= form.label :coingecko, class: "form-label" %>
    <%= form.collection_select :gecko_coin_id, GeckoCoin.all, :id, :name, {}, 
                               data: {'trade-form-target'=>'walletField' },
                               class: "search form-select form-select-sm" %>
  </div>
  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, required: true, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :code, class: "form-label" %>
    <%= form.text_field :code, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :reference_price, class: "form-label" %>
    <%= form.text_field :reference_price, class: "form-control" %>
  </div>
  <div class="mb-3 form-check">
    <%= form.check_box :hide, class: "form-check-input" %>
    <%= form.label :hide, class: "form-check-label" %>
  </div>

  <%= form.submit action, class: "btn btn-primary" %>
<% end %>

app/views/coins/_reference_price_td.html.erb
<td  data-controller="dynamic-field" 
    data-action="click->dynamic-field#displayForm"
    data-dynamic-field-url-value="<%= reference_price_coin_path(coin) %>"
    class='user-input'>
    <div class='reference_price_value' 
        data-dynamic-field-target="display"><%= coin.reference_price %></div>
    <%= form_for coin, url: coin_path(coin),
                  method: :put, remote: true, local: false, 
                  data: {action: "ajax:error->dynamic-field#handleError ajax:success->dynamic-field#handleSuccess"} do |form| %>
    <%= form.hidden_field :reference_price, 
                          class: "form-control form-control-sm", 
                          data: { 'action' => "focusout->dynamic-field#updateValue",
                                  'dynamic-field-target' => "input" } %>
    <% end %>
</td>

app/views/coins/edit.html.erb
<h1><%=" #{t 'app.actions.edit'} #{@coin.display_name}" %></h1>

<%= render 'form', method: :put, url: coin_path(@coin), action: "Modifier" %>

app/views/coins/index.html.erb
<h1><%= t('.title').capitalize %></h1>

<table class='table table-sm'>
  <thead>
    <tr>
      <th scope='col'>Crypto</th>
      <th scope='col' data-bs-toggle="tooltip" data-bs-placement="top" title="<%= @main_currency.upcase %>"><%= t('.market_price')%></th>
      <th scope='col' data-bs-toggle="tooltip" data-bs-placement="top" title="<%= @main_currency.upcase %>"><%= t('.ref_price') %></th>
      <th scope='col'>Masquer</th>
      <th scope='col'></th>
    </tr>
  </thead>
  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.display_name %> </td>
        <td><%= coin.market_value(@main_currency) %> </td>
        <%= render 'reference_price_td', coin: coin %>
        <td>
          <% if coin.hide %>
            <i class="fas fa-check"></i>
          <% end %>
        </td>
        <td class='text-end'>
          <%= icon_link_to('Trades', "fas fa-exchange-alt", coin_trades_path(coin)) %>
          <%= icon_link_to('Modifier', "far fa-edit",  edit_coin_path(coin)) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new_coin'), new_coin_path, class: 'btn btn-info' %>

app/views/coins/new.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form', method: :post, url: coins_path, action: 'Créer' %>

app/views/coins/reference_price.html.erb
<%= number_with_precision(@coin.reference_price, precision: 2)  %>

app/views/coins/total.html.erb
<%= number_with_precision @total_quantity, precision: current_user.precision %>

app/views/coins/variation_from_reference.html.erb
<%= variation_from_reference(@coin) %>